# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Tkinter App/hack.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push6.sizePolicy().hasHeightForWidth())
        self.push6.setSizePolicy(sizePolicy)
        self.push6.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push6.setObjectName("push6")
        self.gridLayout.addWidget(self.push6, 3, 2, 1, 1)
        self.push7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push7.sizePolicy().hasHeightForWidth())
        self.push7.setSizePolicy(sizePolicy)
        self.push7.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push7.setObjectName("push7")
        self.gridLayout.addWidget(self.push7, 4, 0, 1, 1)
        self.pushMinus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushMinus.sizePolicy().hasHeightForWidth())
        self.pushMinus.setSizePolicy(sizePolicy)
        self.pushMinus.setStyleSheet("QPushButton{    \n"
"    color: rgb(22, 24, 21);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"    background-color: rgb(255, 231, 97);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(235, 255, 55);\n"
"}\n"
"")
        self.pushMinus.setObjectName("pushMinus")
        self.gridLayout.addWidget(self.pushMinus, 2, 4, 1, 1)
        self.push2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push2.sizePolicy().hasHeightForWidth())
        self.push2.setSizePolicy(sizePolicy)
        self.push2.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push2.setObjectName("push2")
        self.gridLayout.addWidget(self.push2, 2, 1, 1, 1)
        self.pushDel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushDel.sizePolicy().hasHeightForWidth())
        self.pushDel.setSizePolicy(sizePolicy)
        self.pushDel.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.pushDel.setObjectName("pushDel")
        self.gridLayout.addWidget(self.pushDel, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 75 36pt \"Cantarell\";")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.pushDevide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushDevide.sizePolicy().hasHeightForWidth())
        self.pushDevide.setSizePolicy(sizePolicy)
        self.pushDevide.setStyleSheet("QPushButton{    \n"
"    color: rgb(22, 24, 21);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"    background-color: rgb(255, 231, 97);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(235, 255, 55);\n"
"}\n"
"")
        self.pushDevide.setObjectName("pushDevide")
        self.gridLayout.addWidget(self.pushDevide, 4, 4, 1, 1)
        self.push9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push9.sizePolicy().hasHeightForWidth())
        self.push9.setSizePolicy(sizePolicy)
        self.push9.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push9.setObjectName("push9")
        self.gridLayout.addWidget(self.push9, 4, 2, 1, 1)
        self.pushClear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushClear.sizePolicy().hasHeightForWidth())
        self.pushClear.setSizePolicy(sizePolicy)
        self.pushClear.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.pushClear.setObjectName("pushClear")
        self.gridLayout.addWidget(self.pushClear, 1, 0, 1, 2)
        self.push1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push1.sizePolicy().hasHeightForWidth())
        self.push1.setSizePolicy(sizePolicy)
        self.push1.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push1.setObjectName("push1")
        self.gridLayout.addWidget(self.push1, 2, 0, 1, 1)
        self.pushDot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushDot.sizePolicy().hasHeightForWidth())
        self.pushDot.setSizePolicy(sizePolicy)
        self.pushDot.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.pushDot.setObjectName("pushDot")
        self.gridLayout.addWidget(self.pushDot, 5, 2, 1, 1)
        self.pushEqual = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushEqual.sizePolicy().hasHeightForWidth())
        self.pushEqual.setSizePolicy(sizePolicy)
        self.pushEqual.setStyleSheet("QPushButton{    \n"
"    color: rgb(22, 24, 21);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"    background-color: rgb(255, 231, 97);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(235, 255, 55);\n"
"}\n"
"")
        self.pushEqual.setObjectName("pushEqual")
        self.gridLayout.addWidget(self.pushEqual, 5, 4, 1, 1)
        self.pushPlus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushPlus.sizePolicy().hasHeightForWidth())
        self.pushPlus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushPlus.setFont(font)
        self.pushPlus.setStyleSheet("QPushButton{    \n"
"    color: rgb(22, 24, 21);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"    background-color: rgb(255, 231, 97);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(235, 255, 55);\n"
"}\n"
"")
        self.pushPlus.setObjectName("pushPlus")
        self.gridLayout.addWidget(self.pushPlus, 1, 4, 1, 1)
        self.push4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push4.sizePolicy().hasHeightForWidth())
        self.push4.setSizePolicy(sizePolicy)
        self.push4.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push4.setObjectName("push4")
        self.gridLayout.addWidget(self.push4, 3, 0, 1, 1)
        self.push8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push8.sizePolicy().hasHeightForWidth())
        self.push8.setSizePolicy(sizePolicy)
        self.push8.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push8.setObjectName("push8")
        self.gridLayout.addWidget(self.push8, 4, 1, 1, 1)
        self.pushMultiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushMultiply.sizePolicy().hasHeightForWidth())
        self.pushMultiply.setSizePolicy(sizePolicy)
        self.pushMultiply.setStyleSheet("QPushButton{    \n"
"    color: rgb(22, 24, 21);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"    background-color: rgb(255, 231, 97);\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(235, 255, 55);\n"
"}\n"
"")
        self.pushMultiply.setObjectName("pushMultiply")
        self.gridLayout.addWidget(self.pushMultiply, 3, 4, 1, 1)
        self.push3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push3.sizePolicy().hasHeightForWidth())
        self.push3.setSizePolicy(sizePolicy)
        self.push3.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push3.setObjectName("push3")
        self.gridLayout.addWidget(self.push3, 2, 2, 1, 1)
        self.push0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push0.sizePolicy().hasHeightForWidth())
        self.push0.setSizePolicy(sizePolicy)
        self.push0.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push0.setObjectName("push0")
        self.gridLayout.addWidget(self.push0, 5, 0, 1, 2)
        self.push5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push5.sizePolicy().hasHeightForWidth())
        self.push5.setSizePolicy(sizePolicy)
        self.push5.setStyleSheet("QPushButton{    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(39, 39, 39);\n"
"    font: 75 24pt \"Bitstream Vera Sans\";\n"
"\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.push5.setObjectName("push5")
        self.gridLayout.addWidget(self.push5, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.push1.clicked.connect(self.methode_1)
        self.push2.clicked.connect(self.methode_2)
        self.push3.clicked.connect(self.methode_3)
        self.push4.clicked.connect(self.methode_4)
        self.push5.clicked.connect(self.methode_5)
        self.push6.clicked.connect(self.methode_6)
        self.push7.clicked.connect(self.methode_7)
        self.push8.clicked.connect(self.methode_8)
        self.push9.clicked.connect(self.methode_9)
        self.push0.clicked.connect(self.methode_0)
        self.pushClear.clicked.connect(self.methode_clear)
        self.pushDel.clicked.connect(self.methode_del)
        self.pushDevide.clicked.connect(self.methode_dev)
        self.pushPlus.clicked.connect(self.methode_plus)
        self.pushMinus.clicked.connect(self.methode_minus)
        self.pushMultiply.clicked.connect(self.methode_multiply)
        self.pushDot.clicked.connect(self.methode_dot)
        self.pushEqual.clicked.connect(self.methode_equal)

    def methode_1(self):
        text =self.label.text()
        self.label.setText(text+"1")
    def methode_2(self):
        text =self.label.text()
        self.label.setText(text+"2")
    def methode_3(self):
        text =self.label.text()
        self.label.setText(text+"3")
    def methode_4(self):
        text =self.label.text()
        self.label.setText(text+"4")
    def methode_5(self):
        text =self.label.text()
        self.label.setText(text+"5")
    def methode_6(self):
        text =self.label.text()
        self.label.setText(text+"6")
    def methode_7(self):
        text =self.label.text()
        self.label.setText(text+"7")
    def methode_8(self):
        text =self.label.text()
        self.label.setText(text+"8")
    def methode_9(self):
        text =self.label.text()
        self.label.setText(text+"9")
    def methode_0(self):
        text =self.label.text()
        self.label.setText(text+"0")

    def methode_clear(self):
        text =self.label.text()
        self.label.setText("")
    def methode_dot(self):
        text =self.label.text()
        self.label.setText(text+".")
    def methode_del(self):
        text =self.label.text()
        self.label.setText(text[:len(text)-1])
    def methode_plus(self):
        text =self.label.text()
        self.label.setText(text+"+")
    def methode_minus(self):
        text =self.label.text()
        self.label.setText(text+"-")
    def methode_multiply(self):
        text =self.label.text()
        self.label.setText(text+"*")
    def methode_dev(self):
        text =self.label.text()
        self.label.setText(text+"/")
    def methode_equal(self):
        text =self.label.text()
        try:
            ans=eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.push6.setText(_translate("MainWindow", "6"))
        self.push6.setShortcut(_translate("MainWindow", "6"))
        self.push7.setText(_translate("MainWindow", "7"))
        self.push7.setShortcut(_translate("MainWindow", "7"))
        self.pushMinus.setText(_translate("MainWindow", "-"))
        self.pushMinus.setShortcut(_translate("MainWindow", "-"))
        self.push2.setText(_translate("MainWindow", "2"))
        self.push2.setShortcut(_translate("MainWindow", "2"))
        self.pushDel.setText(_translate("MainWindow", "DEL"))
        self.pushDel.setShortcut(_translate("MainWindow", "Del"))
        self.pushDevide.setText(_translate("MainWindow", "%"))
        self.pushDevide.setShortcut(_translate("MainWindow", "/"))
        self.push9.setText(_translate("MainWindow", "9"))
        self.push9.setShortcut(_translate("MainWindow", "9"))
        self.pushClear.setText(_translate("MainWindow", "CLEAR"))
        self.pushClear.setShortcut(_translate("MainWindow", "Backspace"))
        self.push1.setText(_translate("MainWindow", "1"))
        self.push1.setShortcut(_translate("MainWindow", "1"))
        self.pushDot.setText(_translate("MainWindow", "."))
        self.pushDot.setShortcut(_translate("MainWindow", "."))
        self.pushEqual.setText(_translate("MainWindow", "="))
        self.pushEqual.setShortcut(_translate("MainWindow", "="))
        self.pushPlus.setText(_translate("MainWindow", "+"))
        self.pushPlus.setShortcut(_translate("MainWindow", "+"))
        self.push4.setText(_translate("MainWindow", "4"))
        self.push4.setShortcut(_translate("MainWindow", "4"))
        self.push8.setText(_translate("MainWindow", "8"))
        self.push8.setShortcut(_translate("MainWindow", "8"))
        self.pushMultiply.setText(_translate("MainWindow", "x"))
        self.pushMultiply.setShortcut(_translate("MainWindow", "*"))
        self.push3.setText(_translate("MainWindow", "3"))
        self.push3.setShortcut(_translate("MainWindow", "3"))
        self.push0.setText(_translate("MainWindow", "0"))
        self.push0.setShortcut(_translate("MainWindow", "0"))
        self.push5.setText(_translate("MainWindow", "5"))
        self.push5.setShortcut(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
